### ISSUE TITLE
Crashing issue with Linux

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#116]
This is from the Steam workshop "Report Issues here" post.  It looks like Firaxis' trickery with include("NotificationPanel_", true) at the end of NotificationPanel.lua is creating a loop because that trickery ends up "including" notificationpanel_CQUI_basegame.lua, which then has an _include("NotificationPanel")_ itself...

I suggested a fix, don't know if they'll be able to try it on our behalf, but basically only load NotificationPanel if one of the functions is nil.

```
-- Firaxis added that 'include("NotificationPanel_", true); to the end of their NotificationPanel.lua, which is causing a loop where it loads this file again.
-- We need to try and protect against loading a second time...
-- This function is one of the functions extended in notificationpanel_CQUI.lua, it is global, or at least in the NotificationPanel context
if (OnTechBoostActivateNotification == nil) then
    include("NotificationPanel");

    include("notificationpanel_CQUI.lua");
end

```
Also we should remember to update the version number thingy in CQUI_main I suppose...

Error snippet:
```

cqui_main: CQUI Loaded! Update for v1.0.2.39 (2020-06-21)
Runtime Error: C stack overflow: too many (128) nested C function calls.

stack traceback:
[C]: in function 'lInclude'
C:\Emu\AppAssets\Base\Assets\ui\techandcivicunlockables.lua:264: in function '(main chunk)'
[C]: in function 'lInclude'
C:\Emu\AppAssets\Base\Assets\ui\tooltiphelper.lua:12: in function '(main chunk)'
[C]: in function 'lInclude'
C:\Emu\AppAssets\Base\Assets\ui\panels\notificationpanel.lua:3: in function '(main chunk)'
[C]: in function 'lInclude'
\home\dave\.local\share\Steam\steamapps\workshop\content\289070\2115302648\Assets\UI\Panels\notificationpanel_CQUI_basegame.lua:4: in function '(main chunk)'
[C]: in function 'lInclude'
C:\Emu\AppAssets\Base\Assets\ui\panels\notificationpanel.lua:1895: in function '(main chunk)'
Lua callstack:

@C:\Emu\AppAssets\Base\Assets\ui\tooltiphelper.lua:12
@C:\Emu\AppAssets\Base\Assets\ui\panels\notificationpanel.lua:3
@\home\dave\.local\share\Steam\steamapps\workshop\content\289070\2115302648\Assets\UI\Panels\notificationpanel_CQUI_basegame.lua:4
@C:\Emu\AppAssets\Base\Assets\ui\panels\notificationpanel.lua:1895
@\home\dave\.local\share\Steam\steamapps\workshop\content\289070\2115302648\Assets\UI\Panels\notificationpanel_CQUI_basegame.lua:4
Error loading file where=C:\Emu\AppAssets\Base\Assets\ui\tooltiphelper.lua:12: , file=C:\Emu\AppAssets\Base\Assets\ui\techandcivicunlockables.lua
Runtime Error: C stack overflow: too many (128) nested C function calls.

```

**Comment by Infixo** [comment]
I wrote in my initial issue report:
There is no need for _basegame, _xp1 and _xp2 files. Also no need to use ReplaceUIScript in the .modinfo.
I am not sure why complicate things?

**Comment by the-m4a** [comment]
the _basegame, _xp1, _xp2 was following what had already been in place, the lack of documentation from Firaxis on how to best do such things was a contributing factor.  If there are other, more resilient and reasonable ways to do this, I am not opposed to it.

In this case, what would be your suggestion?  We have a few functions declared in notificationpanel_CQUI.lua that call their "BASE" counterparts, and that's it:

```
BASE_CQUI_OnTechBoostActivateNotification = OnTechBoostActivateNotification;
BASE_CQUI_OnCivicBoostActivateNotification = OnCivicBoostActivateNotification;
BASE_CQUI_OnNotificationAdded = OnNotificationAdded;
BASE_CQUI_LateInitialize = LateInitialize;
BASE_CQUI_RegisterHandlers = RegisterHandlers;

```

**Comment by Infixo** [comment]
Let’s start from the begining.
The idea behind this include(xxx_) mechanics is that some functionalities can be added without the need to change the base file. It is kind of workaround for some Lua limitations. Very useful when adding some repeatable elements.
An excellent example is in More Lenses. Other mods can add new lenses without modifying the ML mod itself. It is really neatly done.

**Comment by Infixo** [comment]
How this works.
When Lua encounters include(zzz) then this include is replaced with the text found in zzz.lua.
However this always treated as a pattern, so any file that starts with zzz is matching. This allows to do multiple includes at once.
Eventually , you end with one big .lua file that has all those zzz*.lua inside it.
In our case with Notifications, this will be main file, exp1 and exp2 files from Firaxis and cqui’s notification_cqui.lua. One big file and all Content is executed.
So, there is no need for cqui to replace anything and hence my comment.

**Comment by Infixo** [comment]
And our changes for base functions will work because this include is at the end if the file, so we can safely change the functions and then call base_xxx. Other files can do the same because there is always a base function - a chain is created that way.

**Comment by alimulhuda** [comment]
I can double check all I'm saying here this weekend, but I'll say what I can remember from memory right now. I was also working on this after work at night so I could be mistaken in what I say here.

The wildcard include introduced by the new version does not let us specify order. If we wanted to overwrite functions from something in Expansion1 or Expansion2 then we would need to load our files after their files. Right now we don't overwrite anything from the Expansion1 or Expansion2 files, so it should be okay, but I didn't want to bake that limitation into the file loading.

The pattern matching is not done on the start of the file but anywhere in the filename, so if we did a wildcard include for zzz, then it would match `zzzabc.lua`, `abczzz.lua`, `abzzzcd.lua`. Not really relevant for this talk but more of an FYI.

When I was trying it out I also saw that doing exactly what you suggested(i.e. removing the _basegame, _xp1 and _xp2 files, and getting rid of ReplaceUIScript in the .modinfo) did not work. It did not include the remaining `notificationpanel_CQUI_basegame.lua` file. I had a print statement at the top of that file as well as the unmodded game files, and I was seeing only the statements from the unmodded game files. That led me to assume that the string matching they do is case sensitive. So I tried changing the filename and all references to the file to `NotificationPanel_CQUI_basegame.lua`, and that seemed to work but it was loading the basegame then Expansion2 then CQUI then Expansion1.

So I did things the way they are because I wanted to ensure CQUI loads after all unmodded game files. Any solution that ensures that order should be good. I also agree that simpler is better, but I couldn't get the simpler solutions to work properly.

**Comment by Infixo** [comment]
Maybe I am missing something, but why do you want to include notificationpanel_CQUI_basegame.lua? There is no functionality there. Only notificationpanel_CQUI.lua is needed.

**Comment by Infixo** [comment]
And yes, the include order is undetermined and that is why it is used to just add separate, repeatable elements, like new notifications. Firaxis knows that and their exp1 and exp2 files are totally independent. And the same should be with all other mods. Just add new notifications or modify base functions.

**Comment by alimulhuda** [comment]
> Maybe I am missing something, but why do you want to include notificationpanel_CQUI_basegame.lua in the first place? There is no functionality there. Only notificationpanel_CQUI.lua is needed.

That one was due to another error I saw. For now assume that what I said in last post is true and that we need ReplaceUIScript. That means somewhere we would have to include the basegame `NotificationPanel`. When I tried adding that include line at the top of `notificationpanel_CQUI.lua` I was getting an error which was complaining about some undefined type that is defined in `NotificationPanel`. My guess is they run some kind of static file checker on each file before they expand the include directives. Having the _basegame file allowed it to work within their system. The other option was to remove the type specification (`NotificationType`) that the system was complaining about.

**Comment by alimulhuda** [comment]
@the-m4a The include guard idea you had seems like it could work. I was thinking maybe something like this would be more future proof and explicit.
```
if (bLoadedNotificationpanelCQUIBasegame == nil) then
    bLoadedNotificationpanelCQUIBasegame = true;
    include("NotificationPanel");

    include("notificationpanel_CQUI.lua");
end
```

**Comment by Infixo** [comment]
I did the fix locally and it was working. When you mentioned it - there was something with the type mismatch, I don’t remember the details now, but I think I solved it. I am abroad currently, I will check what exactly I did in a couple of days when I am back at home.

**Comment by the-m4a** [comment]
It would be nice if we could somehow force things to behave like the Linux environment.  Good info and ideas above, you guys, thanks

**Comment by alimulhuda** [comment]
Short of running a virtual machine, I'm not sure if there is a good and safe way to try Linux stuff. Don't know about you but I'm not adventurous enough to try Linux gaming, and Linux gaming in a VM would be way too much "fun".

**Comment by chaorace** [comment]
I happen to use a Linux box, feel free to hit me up if you need testing.

I just so happen to have patched this issue up on my personal branch yesterday. I didn't see anyone else complaining, so I just assumed it was something odd happening on my specific machine.

I went ahead and submitted a PR with my patch for this as #117. I also ended up fixing a casing issue in our version of the ML integration that broke the minimap on Linux.

There still seems to be an issue affecting the world tracker, but it looks like there's already discussion regarding that in #36

**Comment by the-m4a** [comment]
Hmm... I potentially signed off on the previous fix a bit too early, perhaps :/  I brought it up for additional testing after @alimulhuda 's comment and now I'm not seeing that notificationpanel_CQUI.lua is getting loaded at all.  
![image](https://user-images.githubusercontent.com/8787640/88975670-75eeab80-d26f-11ea-9a3f-c79964d05eac.png)

**Comment by Infixo** [comment]
@the-m4a Was this fixed with PR #117 or not? Because #117 is exactly what I was talking about. Should I still check anything?

**Comment by the-m4a** [comment]
it doesn't look like it.  I thought it was, now I'm not sure why it appeared to work when looking at those changes and not now.  Maybe some goofiness with Git and my local copy (like changes I'd made in a different branch... or maybe I hadn't updated the branch locally when checking?  I don't know).

I have confirmed that I have the files from the master branch now... but - how does the current notificationpanel_CQUI get loaded into the notificationpanel context without the replacescript?

**Comment by chaorace** [comment]
@the-m4a Have you tried loading the patch from my comment [here](https://github.com/civfanatics/CQUI_Community-Edition/pull/117#issuecomment-666354470)? I suspect that notificationpanel is failing to load due to other import errors elsewhere.

@Infixo The mod no longer crashes on Linux, but it's still not playable. There are lingering issues breaking the minimap panel and the worldtracker.

**Comment by chaorace** [comment]
@the-m4a Regarding how it's being imported. The base game seems to have been recently updated to automatically hook NotificationPanel_* files. See this line from the vanilla NotificationPanel.lua file:
> include("NotificationPanel_", true);

Actually... can you confirm the file has that line on the Windows release? If it were missing, that might explain a few things.

**Comment by Infixo** [comment]
@chaorace Win file has exactly the same line.

**Comment by the-m4a** [comment]
it's the same on Windows:

```
-- This wildcard include will include all loaded files beginning with "NotificationPanel_"
-- This method replaces the uses of include("NotificationPanel") in files that want to override 
-- functions from this file. If you're implementing a new "NotificationPanel_" file DO NOT include this file.
include("NotificationPanel_", true);

```

And yeah, no evidence that the file is being loaded.  Even tried adding an ImportFiles specifically for the file with a loadorder of -1, just to ensure it'd be "there" by the time base NotificationPanel.lua did that Include function, but no dice.

**Comment by Infixo** [comment]
I managed to load it properly. I am doing another test, gimme few more minutes.

**Comment by Infixo** [comment]
Ok, so the problem is caused by the file name.
I changed the file name back to the "original" NotificationPanel_CQUI.lua and it loaded.

**Comment by Infixo** [comment]
My theory is that Windows on a system level doesn't care about letter casing, but Lua actually does. And include uses pattern matching, so it looks for this specific file name: "NotificationPanel_".
Second theory is that this additional parameter "true" may do something? I don't know what it does exactly.

**Comment by Infixo** [comment]
I would suggest changing the file name and corresponding entries in .modinfo and test if this also fixes Linux. I will post a branch in a sec.

**Comment by the-m4a** [comment]
Is the "include" a Firaxis thing (something the game DLL implements while parsing the Lua) or a component of whatever Lua compiler engine they're using?
Either way - it seems like the include with single parameter is case insensitive (at least on windows), while this one isn't... maybe the "true" is enforcing the casing on the wild card search?  I wonder how it behaves if forced as "false" (it doesn't fix this, just curious what it does)

**Comment by chaorace** [comment]
Yeah, seems like an inconsistency between the implementation of include on Windows vs. Linux.
For some reason, wildcard include is *more* specific on Windows. Bizarre!

For what it's worth, the Linux version will tolerate UpperCase file names on the actual filesystem, so long as the modinfo file uses full lowercase filenames. Check out the [MoreLenses repo](https://github.com/astog/MoreLenses) for a demonstration of this behavior. Note the difference in filename in the modinfo vs the repo. I can confirm this pattern works just fine on Linux

So yeah, if we want wildcard includes to work consistently, we need to make sure the actual filenames are consistent with the Windows version, while making the modinfo names consistent with the Linux/OSX version.

**Comment by alimulhuda** [comment]
I think whatever form of Lua they are using is something custom, I don't think "real" Lua has the type specifications ( variableName:typeName), or the include statement (from I could find it's requires or something like that), or hstructures.

Regarding the recursive issue. I still think we should revert the changes from #117 and instead do the include guard idea that the-m4a had. I consider that the least likely to have unintended consequences and the lowest risk change we could make, assuming that the include guard actually solves the recursive include issue on Linux. The include guard is also very clear on what is being accomplished, and avoids baking in unintuitive system specific knowledge into the mod.

**Comment by chaorace** [comment]
@alimulhuda I disagree, but only because taking such a stance means we would need to guard against this every since time we ever encounter a wildcard include. That's a huge pain, especially when it comes to maintaining integrations.

**Comment by chaorace** [comment]
Why not just change the file naming format so that it no longer collides with the wildcard include statement?

**Comment by alimulhuda** [comment]
From what I was seeing on windows that would not work. The wildcard matches to any part of the filename not just the beginning.

**Comment by chaorace** [comment]
Are you certain about that? I am 100% sure that changing the filename pattern in this way works on Linux, I checked just yesterday. The matcher _should_ give up if the text prior to "_" is not an exact match.

**Comment by chaorace** [comment]
(paging @astog on the off chance he might be able to comment on his experience with wildcard include)

**Comment by alimulhuda** [comment]
While I was messing around with this issue, back when the patch dropped, I remember trying to change the filename to CQUI_NotificationPanel_basegame, and it triggered recursive includes on windows. But I'm not 100% certain since I was working late and I don't fully trust myself in that state. Someone should probably test my claim on windows.

Right now I don't think I'll be able to make time to check stuff until maybe Sunday. Anytime I start messing with code it eats up more time then I intend on spending, so I'm avoiding code right now.

**Comment by chaorace** [comment]
Quick correction on my part:

The modinfo has to be consistent with the filename, disregard what I said previously. I retested ML and realized that it wasn't loading after restarting the game client. Whoops!

So that leaves us with a situation where we apparently need to use UpperCase filenames for vanilla wildcard includes to work correctly on Windows, BUT we have to use lowercase filenames for file replacement to work on Linux... kind of a catch-22

I guess it will all work out OK as long as we make sure to use full lowercase filenames in our own include statements. The tricky part is dealing with the vanilla wildcard include statements...

Maybe we should build a list of all vanilla wildcard include patterns and ban those filenames preemptively?

**Comment by chaorace** [comment]
I went ahead and grepped the game files. Looks like we should be fine as long as we're careful to avoid creating file names with following patterns:

* CivicsTreeIconLoader_
* CivilopediaPage_
* EndGameMenu_
* NotificationPanel_
* PopupPriorityLoader_
* TechAndCivicUnlockables_
* TechFilterFunctions_
* TutorialLoader_
* WorldTrackerItem_

Full grep results:
```
rg 'include\(".*_"'
base/assets/ui/worldtracker.lua
12:include("WorldTrackerItem_", true);
16:include("CivicsTreeIconLoader_", true);

base/assets/ui/popups/playerchange.lua
6:include("PopupPriorityLoader_", true);

base/assets/ui/tutorialuiroot.lua
10:include("TutorialLoader_", true);	-- Additional tutorial event handlers.

base/assets/ui/screens/civicstree.lua
21:include("CivicsTreeIconLoader_", true);

base/assets/ui/techandcivicunlockables.lua
264:include("TechAndCivicUnlockables_", true);

base/assets/ui/menus/ingametopoptionsmenu.lua
12:include("PopupPriorityLoader_", true);

base/assets/ui/menus/hotseatbackground.lua
4:include("PopupPriorityLoader_", true);

base/assets/ui/panels/techfilterfunctions.lua
21:include("TechFilterFunctions_", true);

base/assets/ui/panels/pausepanel.lua
3:include("PopupPriorityLoader_", true);

base/assets/ui/panels/notificationpanel.lua
1895:include("NotificationPanel_", true);

base/assets/ui/civilopedia/civilopediascreen.lua
13:include("CivilopediaPage_", true);

base/assets/ui/endgame/endgamemenu.lua
1326:include("EndGameMenu_", true);

base/assets/ui/choosers/civicschooser.lua
9:include("CivicsTreeIconLoader_", true);

dlc/expansion2/ui/additions/worldcongresspopup.lua
10:include("PopupPriorityLoader_", true);

dlc/expansion2/ui/additions/worldcongressbetweenturns.lua
6:include("PopupPriorityLoader_", true);

dlc/expansion2/ui/additions/worldcongressintro.lua
6:include("PopupPriorityLoader_", true);
```

**Comment by Infixo** [comment]
@chaorace 
Lua has its own system file, a flat structure. All files listed in “ImportFiles” section are loaded into that flat structure, the catalogs in the original system don’t matter.
Once loaded, they can normally accessed, read, etc. BUT all these functions are cut from Lua in Civ. The only function that actually accesses that internal file system is imho include.
Next thing - include uses pattern matching, so the letter casing matters. And I can bet it is the same in Linux.
Btw, the “normal” issue with Linux files comes from the fact that .modinfo is processed by the game engine, not Lua engine. Hence the little different behavior between Win and Linux.
Anyway, can you test my branch. It is working on Windows properly. Just change the file name properly. If it is working on Linux, then the problem is fixed.

**Comment by chaorace** [comment]
I appreciate the refresher. Thank you very much.

I do want to assert something though... there absolutely is an inconsistency in the way the include statement is operating. If there weren't, we would be experiencing the recursion issue on all platforms. imo, it's a bug in Aspyr's implementation.

In any case, I'm testing your branch now. Will report back with results in a moment.

**Comment by Infixo** [comment]
Make sure to change the file name. The branch still has lowercase.

**Comment by chaorace** [comment]
Hey @Infixo , sorry for being blind, but I can't seem to find the branch you're referring to. I checked your fork and the branches here, but all I can seem to find is the dead code branch.

Could you help me out with a link?

**Comment by Infixo** [comment]
> I appreciate the refresher. Thank you very much.
> 
> I do want to assert something though... there absolutely is an inconsistency in the way the include statement is operating. If there weren't, we would be experiencing the recursion issue on all platforms. imo, it's a bug in Aspyr's implementation.
>
Not necessarily a bug. Could be a conscious design decision.
I assume Asypr is working with the assumption that all game files should be the same as in windows which is sort of master (ex. For UI maybe).
So they actually had to solve an issue : how to load multiple files with include that is using UpperCase knowing that files will be renamed to lowercase? Answer: include must work a bit differently, i.e. case-insensitive.

**Comment by Infixo** [comment]
https://github.com/civfanatics/CQUI_Community-Edition/tree/infixo-116-notifications

**Comment by chaorace** [comment]
Now I'm even more confused! What filename should I be changing, exactly? This branch seems entirely identical to the current master.

For what it's worth, the branch loads just fine on Linux, as-is, without any adjustments at all.

Here's the log data:
```
DebugHotloadCache: GameDebug initialized!
Test: Test.LUA loaded!
JoiningRoom: OnFinishedGameplayContentConfigure() g_waitingForContentConfigure=true
JoiningRoom: OnFinishedGameplayContentConfigure() g_waitingForContentConfigure=true
LoadGameMenu: LoadGameMenu::OnLoadYes() leaving the network session.
cqui_main: CQUI Loaded! Update for v1.0.2.39 (2020-06-21)
WorldCongress: Initializing World Congress Lua
LoadScreen: true
LoadScreen: false
LoadScreen: true
LoadScreen: true
MapLabelManager: RHEIC OCEAN (6.8663624751916e-44, 1.1210387714599e-43)
Error opening/reading where=, file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Assets\Expansion1\Replacements\WorldTracker_Expansion1.lua
MinimapPanel: Governor Builder Index = 4
MinimapPanel: Governor Builder Aquaculture hash = -122625491
MinimapPanel: Governor Builder Parks Rec hash = 1630405030
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua:411: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua:411: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:9: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:6: in function '(main chunk)'
	[C]: in function '(anonymous)'
Lua callstack:

@C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:9
@C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6
@C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:6
Error loading file where=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:9: , file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua
MinimapPanel: Governor Builder Index = 4
MinimapPanel: Governor Builder Aquaculture hash = -122625491
MinimapPanel: Governor Builder Parks Rec hash = 1630405030
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1558: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1558: in function 'Initialize'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1600: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:6: in function '(main chunk)'
	[C]: in function '(anonymous)'
Lua callstack:

@C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6
@C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:6
Error loading file where=C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6: , file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua
MinimapPanel: Instance Manager built with bad Root Control [MapOptionInstance] [ToggleButton]
Runtime Error: C:\Emu\AppAssets\Base\Assets\ui\instancemanager.lua:179: attempt to index a nil value
stack traceback:
	C:\Emu\AppAssets\Base\Assets\ui\instancemanager.lua:179: in function 'BuildInstance'
	C:\Emu\AppAssets\Base\Assets\ui\instancemanager.lua:36: in function 'GetInstance'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:171: in function 'CreateMapOptionButton'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:56: in function 'CreateMapLabelToggle'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:132: in function 'LateInitialize'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1541: in function 'OnInit'
Lua callstack:
TradeOverview: Initializing BTS Trade Support Tracker
TradeRouteChooser: Initializing BTS Trade Route Chooser
TradeRouteChooser: Initializing BTS Trade Support Automater
TradeOriginChooser: Initializing BTS Trade Origin Chooser
ModalLensPanel: Governor Builder Index = 4
ModalLensPanel: Governor Builder Aquaculture hash = -122625491
ModalLensPanel: Governor Builder Parks Rec hash = 1630405030
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua:411: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua:411: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\Panels\modallenspanel.lua:12: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\ModalLensPanel_Expansion1.lua:6: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\ModalLensPanel_Expansion2.lua:6: in function '(main chunk)'
	[C]: in function '(anonymous)'
Lua callstack:

@C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\Panels\modallenspanel.lua:12
@C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\ModalLensPanel_Expansion1.lua:6
@C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\ModalLensPanel_Expansion2.lua:6
Error loading file where=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\Panels\modallenspanel.lua:12: , file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua
ModalLensPanel: Governor Builder Index = 4
ModalLensPanel: Governor Builder Aquaculture hash = -122625491
ModalLensPanel: Governor Builder Parks Rec hash = 1630405030
MapPinPopup: initializing MapTacks.IconOptions(0)
MapPinPopup: Selected 14 columns
DiplomacyDealView: CQUI Diplomacy Deal View for expansion 2 loaded
ModLens_CityOverlap: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ModLens_CityOverlap:           City Overlap Panel
ModLens_CityOverlap: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_CityOverlap.lua:182: operator + is not supported for nil + number
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_CityOverlap.lua:182: in function 'OnReoffsetPanel'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_CityOverlap.lua:279: in function 'Initialize'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_CityOverlap.lua:306: in function '(main chunk)'
	[C]: in function '(anonymous)'
Lua callstack:
Error loading file where=, file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_CityOverlap.lua
ModLens_Resource: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ModLens_Resource:            Resource Panel
ModLens_Resource: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Resource.lua:355: operator + is not supported for nil + number
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Resource.lua:355: in function 'OnReoffsetPanel'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Resource.lua:424: in function 'Initialize'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Resource.lua:448: in function '(main chunk)'
	[C]: in function '(anonymous)'
Lua callstack:
Error loading file where=, file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Resource.lua
TutorialUIRoot: Tutorial: Firaxis in game tutorial prompts.
TutorialUIRoot: Version: 1
TutorialUIRoot: Loading bank of items for tutorial scenario: 'BASE'
MapLabelManager: RHEIC OCEAN (-720.42535400391, 429.20227050781)
MapLabelManager: RHEIC OCEAN (-551.21557617188, -461.38824462891)
MapLabelManager: RHEIC OCEAN (1261.5551757812, -40.199851989746)
MapLabelManager: RHEIC OCEAN (1277.3793945312, -554.77484130859)
MapLabelManager: RHEIC OCEAN (1336.4517822266, 464.08554077148)
MapLabelManager: RHEIC OCEAN (1774.5440673828, -159.53692626953)
LoadScreen: OnLoadGameViewStateDone
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1194: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1194: in function 'GetMinimapMouseCoords'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1324: in function 'ShowMinimapTooltips'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1304: in function 'OnInputHandler'
Lua callstack:
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1194: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1194: in function 'GetMinimapMouseCoords'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1324: in function 'ShowMinimapTooltips'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1304: in function 'OnInputHandler'
Lua callstack:
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1194: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1194: in function 'GetMinimapMouseCoords'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1324: in function 'ShowMinimapTooltips'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1304: in function 'OnInputHandler'
Lua callstack:
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1194: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1194: in function 'GetMinimapMouseCoords'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1324: in function 'ShowMinimapTooltips'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1304: in function 'OnInputHandler'
Lua callstack:

```

**Comment by Infixo** [comment]
Notificationpanel_CQUI.lua must be renamed to NotificationPanel_CQUI.lua.
Branch has changes to .modinfo and a print in this file to check that it loads properly.

**Comment by Infixo** [comment]
Ok, it seems that I pushed it too fast, sorry. My bad.

To summarize it. Take the master and
a change the filename to be NotificationPanel_CQUI.lua
B modify .modinfo accordingly
C add some print to that lua to see that it loads

That’s it

**Comment by chaorace** [comment]
Loading "NotificationPanel.lua" seems to be working. Looks like you were right on the money! Guess we'll just need to be vigilant and make sure filenames in include statements match exactly, so there aren't future surprises.

Diff

```
git --no-pager diff --cached
diff --git a/Assets/UI/Panels/notificationpanel_CQUI.lua b/Assets/UI/Panels/NotificationPanel_CQUI.lua
similarity index 99%
rename from Assets/UI/Panels/notificationpanel_CQUI.lua
rename to Assets/UI/Panels/NotificationPanel_CQUI.lua
index 6601264..8b66ad0 100644
--- a/Assets/UI/Panels/notificationpanel_CQUI.lua
+++ b/Assets/UI/Panels/NotificationPanel_CQUI.lua
@@ -1,3 +1,4 @@
+print("Greetings, from NotificationsPanel_CQUI.lua")
 -- ===========================================================================
 -- Cached Base Functions
 -- ===========================================================================
@@ -113,4 +114,4 @@ function RegisterHandlers()
     
     g_notificationHandlers[NotificationTypes.CIVIC_BOOST].Activate = OnCivicBoostActivateNotification;
     g_notificationHandlers[NotificationTypes.TECH_BOOST].Activate = OnTechBoostActivateNotification;
-end
\ No newline at end of file
+end
diff --git a/CQUI.modinfo b/CQUI.modinfo
index d246afc..bfab1c0 100644
--- a/CQUI.modinfo
+++ b/CQUI.modinfo
@@ -150,7 +150,7 @@
                 <File>Assets/UI/Panels/citypanel.xml</File>
                 <File>Assets/UI/Panels/citypaneloverview.lua</File>
                 <File>Assets/UI/Panels/citypaneloverview.xml</File>
-                <File>Assets/UI/Panels/notificationpanel_CQUI.lua</File>
+                <File>Assets/UI/Panels/NotificationPanel_CQUI.lua</File>
                 <File>Assets/UI/Panels/statusmessagepanel.lua</File>
                 <File>Assets/UI/Panels/statusmessagepanel.xml</File>
                 <File>Assets/UI/Panels/unitpanel_CQUI_basegame.lua</File>
@@ -998,7 +998,7 @@
         <File>Assets/UI/Panels/citypanel.xml</File>
         <File>Assets/UI/Panels/citypaneloverview.lua</File>
         <File>Assets/UI/Panels/citypaneloverview.xml</File>
-        <File>Assets/UI/Panels/notificationpanel_CQUI.lua</File>
+        <File>Assets/UI/Panels/NotificationPanel_CQUI.lua</File>
         <File>Assets/UI/Panels/productionpanel_CQUI.lua</File>
         <File>Assets/UI/Panels/statusmessagepanel.lua</File>
         <File>Assets/UI/Panels/statusmessagepanel.xml</File>
```

Logs:
```
DebugHotloadCache: GameDebug initialized!
Test: Test.LUA loaded!
JoiningRoom: OnFinishedGameplayContentConfigure() g_waitingForContentConfigure=true
JoiningRoom: OnFinishedGameplayContentConfigure() g_waitingForContentConfigure=true
LoadGameMenu: LoadGameMenu::OnLoadYes() leaving the network session.
cqui_main: CQUI Loaded! Update for v1.0.2.39 (2020-06-21)
WorldCongress: Initializing World Congress Lua
LoadScreen: true
LoadScreen: false
LoadScreen: true
LoadScreen: true
MapLabelManager: RHEIC OCEAN (6.8663624751916e-44, 1.1210387714599e-43)
NotificationPanel: Greetings, from NotificationsPanel_CQUI.lua
Error opening/reading where=, file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Assets\Expansion1\Replacements\WorldTracker_Expansion1.lua
MinimapPanel: Governor Builder Index = 4
MinimapPanel: Governor Builder Aquaculture hash = -122625491
MinimapPanel: Governor Builder Parks Rec hash = 1630405030
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua:411: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua:411: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:9: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:6: in function '(main chunk)'
	[C]: in function '(anonymous)'
Lua callstack:

@C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:9
@C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6
@C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:6
Error loading file where=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:9: , file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua
MinimapPanel: Governor Builder Index = 4
MinimapPanel: Governor Builder Aquaculture hash = -122625491
MinimapPanel: Governor Builder Parks Rec hash = 1630405030
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1558: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1558: in function 'Initialize'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1600: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:6: in function '(main chunk)'
	[C]: in function '(anonymous)'
Lua callstack:

@C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6
@C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:6
Error loading file where=C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6: , file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua
MinimapPanel: Instance Manager built with bad Root Control [MapOptionInstance] [ToggleButton]
Runtime Error: C:\Emu\AppAssets\Base\Assets\ui\instancemanager.lua:179: attempt to index a nil value
stack traceback:
	C:\Emu\AppAssets\Base\Assets\ui\instancemanager.lua:179: in function 'BuildInstance'
	C:\Emu\AppAssets\Base\Assets\ui\instancemanager.lua:36: in function 'GetInstance'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:171: in function 'CreateMapOptionButton'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:56: in function 'CreateMapLabelToggle'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:132: in function 'LateInitialize'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1541: in function 'OnInit'
Lua callstack:
TradeOverview: Initializing BTS Trade Support Tracker
TradeRouteChooser: Initializing BTS Trade Route Chooser
TradeRouteChooser: Initializing BTS Trade Support Automater
TradeOriginChooser: Initializing BTS Trade Origin Chooser
ModalLensPanel: Governor Builder Index = 4
ModalLensPanel: Governor Builder Aquaculture hash = -122625491
ModalLensPanel: Governor Builder Parks Rec hash = 1630405030
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua:411: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua:411: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\Panels\modallenspanel.lua:12: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\ModalLensPanel_Expansion1.lua:6: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\ModalLensPanel_Expansion2.lua:6: in function '(main chunk)'
	[C]: in function '(anonymous)'
Lua callstack:

@C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\Panels\modallenspanel.lua:12
@C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\ModalLensPanel_Expansion1.lua:6
@C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\ModalLensPanel_Expansion2.lua:6
Error loading file where=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\Panels\modallenspanel.lua:12: , file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua
ModalLensPanel: Governor Builder Index = 4
ModalLensPanel: Governor Builder Aquaculture hash = -122625491
ModalLensPanel: Governor Builder Parks Rec hash = 1630405030
MapPinPopup: initializing MapTacks.IconOptions(0)
MapPinPopup: Selected 14 columns
DiplomacyDealView: CQUI Diplomacy Deal View for expansion 2 loaded
ModLens_CityOverlap: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ModLens_CityOverlap:           City Overlap Panel
ModLens_CityOverlap: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_CityOverlap.lua:182: operator + is not supported for nil + number
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_CityOverlap.lua:182: in function 'OnReoffsetPanel'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_CityOverlap.lua:279: in function 'Initialize'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_CityOverlap.lua:306: in function '(main chunk)'
	[C]: in function '(anonymous)'
Lua callstack:
Error loading file where=, file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_CityOverlap.lua
ModLens_Resource: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ModLens_Resource:            Resource Panel
ModLens_Resource: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Resource.lua:355: operator + is not supported for nil + number
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Resource.lua:355: in function 'OnReoffsetPanel'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Resource.lua:424: in function 'Initialize'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Resource.lua:448: in function '(main chunk)'
	[C]: in function '(anonymous)'
Lua callstack:
Error loading file where=, file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Resource.lua
TutorialUIRoot: Tutorial: Firaxis in game tutorial prompts.
TutorialUIRoot: Version: 1
TutorialUIRoot: Loading bank of items for tutorial scenario: 'BASE'
MapLabelManager: RHEIC OCEAN (-720.42535400391, 429.20227050781)
MapLabelManager: RHEIC OCEAN (-551.21557617188, -461.38824462891)
MapLabelManager: RHEIC OCEAN (1261.5551757812, -40.199851989746)
MapLabelManager: RHEIC OCEAN (1277.3793945312, -554.77484130859)
MapLabelManager: RHEIC OCEAN (1336.4517822266, 464.08554077148)
MapLabelManager: RHEIC OCEAN (1774.5440673828, -159.53692626953)
LoadScreen: OnLoadGameViewStateDone
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1194: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1194: in function 'GetMinimapMouseCoords'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1324: in function 'ShowMinimapTooltips'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1304: in function 'OnInputHandler'
Lua callstack:
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1194: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1194: in function 'GetMinimapMouseCoords'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1324: in function 'ShowMinimapTooltips'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1304: in function 'OnInputHandler'
Lua callstack:
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1194: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1194: in function 'GetMinimapMouseCoords'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1324: in function 'ShowMinimapTooltips'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1304: in function 'OnInputHandler'
```

**Comment by the-m4a** [comment]
nice work figuring that out @Infixo and @chaorace -- since I missed this with the last PR, I went ahead and verified the changes on my end as well, will create a PR shortly

**Comment by Infixo** [comment]
After this excersise I think we understand much better how Win and Linux behave, so we can come up with one approach and stick to it to avoid any such issues in the future.

I must say that I have thought for a long time that it was some sort of requirement from Linux that all files must be lowercased. But apparently this is not true and yet we still create files and make them lowercased.

I consider Windows version as a "master" so I would like to follow the Win-based rules and conciously apply exceptions to make sure the mod works on Linux out-of-the-box.

My understanding atm.
1. Linux is case-sensitive. The file name must be exactly the same as listed in .modinfo. For some reason Aspyr lowercased all files, so if we are actually replacing the file from the original installation - they MUST be lowercased.
2. If we add a new file then it can be named whatever we want. It can be either lowercased, or UpperCased. Will work on both systems as long as exactly the same name is used in .modinfo. I'd prefer Win approach here i.e. UpperCase because I consider Win version a "master".
3. Files used in include statements. Here is the opposite to p.1 because this is done by Lua engine not the system. Files MUST be UpperCased.

Please note that the mod is slowly abandoning the direct file replacements in favor of file extensions so eventually most of the files will be UpperCased and only the replacements will be lowercased which will also act as a sort of flag saying "hi, I'm a replacement file".

**Comment by chaorace** [comment]
@Infixo I agree on all points, except item 3. On Windows, wildcard includes MUST match exactly, on Linux, wildcard includes are more promiscuous and will pick up matches regardless of casing.

The upshot is basically exactly what you're describing, when it comes to interactions with the base game. Vanilla script files all use UpperCase convention, so they only pull in UpperCase files on Windows.

That being said, if we wrote our own wildcard include statement using lowercase convention, Windows would expect an exact lowercase match, while Linux would still not care and match promiscuously. It's a small distinction, but it's worth describing as painfully as possible. 

In any case, I am in full agreement. Let's use UpperCase convention to implicitly signal a non-replacement file. It's handy as a shorthand AND it also solves the edge-case where the Vanilla game automagically imports a file unexpectedly on the Aspyr port.

**Comment by chaorace** [comment]
To sum it up a different way, for the sake of future readers:

The file replacement mechanism and the lua include statement are different units with their own quirks.

**File replacement** insists on an exact filename match. On Windows, casing differences are tolerated because it is case agnostic. Unix-like systems do not tolerate this, so filenames for replacements must match the casing of the base game files exactly, or else the mod breaks on those platforms.

Worth mentioning: All files on the Aspyr port (for Linux/OSX) are lowercased. Since only the Aspyr port is case sensitive, we adhere to the all lowercase format for the actual, real file names whenever file replacement is utilized.

<table>
<tr>
  <td>Replacement File Name</td>
  <th>Windows</th>
  <th>Linux/OSX</th>
</tr>
<tr>
  <th>NotificationPanel.lua</th>
  <td>OK</td>
  <th>FAILS</th>
</tr>
<tr>
  <th>notificationpanel.lua</th>
  <td>OK</td>
  <td>OK</td>
</tr>
</table>

**The Lua include statement** is implemented differently on Windows vs. the Aspyr port, when it comes to the new "wildcard" functionality. Wildcard includes look like this:

```
include("PrefixOfSomeKind_")
```

The \_ at the end denotes that this particular include statement should try to import any number of files, so long as the given prefix matches up. It would match script names like "PrefixOfSomeKind_Foo" and "PrefixOfSomeKind_Bar", but _not_ like "AnUnrelatedPrefix_Foo".

On the Aspyr port, matches are case-insensitive, so both "PrefixOfSomeKind_Foo" and "prefixofsomekind_foo" would be imported by the above include statement.

The rub here is that, on Windows, the include statement actually demands an exact match, **including casing**. This means that include statements like "prefixofsomekind_foo" will _not_ be imported on Windows, given the above include statement example, while "PrefixOfSomeKind_Foo" _will_ be be imported.

<table>
<tr>
  <td>Import Statement</td>
  <td>Actual File Name</td>
  <th>Windows</th>
  <th>Linux/OSX</th>
</tr>
<tr>
  <td>import("NotificationPanel_")</td>
  <th>NotificationPanel_CQUI.lua</th>
  <td>OK</td>
  <td>OK</td>
</tr>
<tr>
  <td>import("notificationpanel_")</td>
  <th>notificationpanel_CQUI.lua</th>
  <td>OK</td>
  <td>OK</td>
</tr>
<tr>
  <td>import("NotificationPanel_")</td>
  <th>notificationpanel_CQUI.lua</th>
  <th>FAILS</th>
  <td>OK</td>
</tr>
</table>


**To recap how this relates to filename convention:**

The casing inconsistency in the include statement means that unexpected Linux bugs can arise if a mod file gets accidentally picked up by a previously unconsidered wildcard include from the base game files, since those developing on the Windows platform will not experience the same issue.

Since the vanilla files use the same UpperCase pattern for all include statements, across all versions, we can avoid this inconsistency by utilizing UpperCase filenames whenever possible, since that will keep filenames fully aligned with the casing convention utilized by the vanilla game files.

However, because of how the file replacements work (where Linux requires them to be full lowercase), we must make an exception for files that replace base game files and always make those completely lowercase.

<table>
<tr>
  <th></th>
  <th>ExampleFile.lua</th>
  <th>examplefile.lua</th>
</tr>
<tr>
  <th>Replacing Game Files</th>
  <th>AVOID ALWAYS</th>
  <td>OK</td>
</tr>
<tr>
  <th>All Other Script Files</th>
  <td>OK</td>
  <th>AVOID ALWAYS</th>
</tr>
</table>

**Comment by Infixo** [comment]
> @Infixo I agree on all points, except item 3. On Windows, wildcard includes MUST match exactly, on Linux, wildcard includes are more promiscuous and will pick up matches...

Well I just I wrote it very unprecisely, but in the end we agree that include files MUST be UpperCased.

**Comment by Infixo** [comment]
And that long post we should store somewhere for reference, it is a brilliant recap.

**Comment by Infixo** [comment]
So... can we close it? Can any linux-guy confirm that the issue is solved in the master?

**Comment by chaorace** [comment]
@Infixo The last time I tested master 13 days ago this was working. I'll pull in the current version and verify later today

**Comment by chaorace** [comment]
Can confirm that the mod no longer crashes on startup. Worldtracker, minimap, banners, and other items remain broken at present moment.

![1597361543](https://user-images.githubusercontent.com/6462592/90197194-ec28fd00-dd9b-11ea-8f67-a6cdf0a41944.png)

**Comment by the-m4a** [comment]
Anything interesting in the logs (lua, modding, user interface)?  I'd love to figure this out..

**Comment by Infixo** [comment]
This incident was mostly about Notification panel and this was fixed. I propose to close this incident and open a new one for other issues.

**Comment by the-m4a** [comment]
Yeah that works

**Comment by alexeyOnGitHub** [comment]
I use Linux too (Ubuntu 20), but I could not use Civ6 on it. the game refuses to recognize my standard (proprietary) NVidia drivers for GeForce 1070ti, which leads to much worse game performance (at least 2x slower).
plus the linux game version has been lagging in its updates by a lot, so I just boot into Win to play the game instead.

**Comment by chaorace** [comment]
Well I'm going to hit the close button then. I'll open issues on the other problems with additional details sometime this weekend when I get the chance.
