### ISSUE TITLE
[January update] Multiple issues with cities

### ISSUE THREAD

**Issue by Gliptal** [civfanatics/CQUI_Community-Edition#242]
- [x] All cities in the normal view share the same name, although the correct one is displayed in city view. Notifications and every screen I tested also show the correct name. **Fixed in [m4a-jan2021updatesfix](https://github.com/civfanatics/CQUI_Community-Edition/tree/m4a-jan2021updatesfix), with (at least) one regression (see #243).**
![normalview](https://user-images.githubusercontent.com/3907646/106195217-23eff980-61b0-11eb-9e0b-443ac829eaf4.png)
![cityview](https://user-images.githubusercontent.com/3907646/106195224-25b9bd00-61b0-11eb-9ce5-d6dc265d1a5c.jpg)

- [x] Clicking on the text in the card doesn't switch to the city view. Interestingly, clicking on another civ's city card text does correctly open the diplomacy screen.

- [x] Hovering on a city card doesn't display any additional overlay information (work icons, yields).
- [x] City views don't display terrain yields anymore. **Some still aren't working, unsure if it's a new thing or not.**
- [x] Housing and turns to expansion are missing from city cards. Built districts as well, and I assume the unassigned citizen icon as well.
![stats](https://user-images.githubusercontent.com/3907646/106196386-a5945700-61b1-11eb-8c77-daa6fef9b3a0.png)

- [x] The City Strike button isn't relocated anymore.
![strike](https://user-images.githubusercontent.com/3907646/106200406-3883c000-61b7-11eb-8047-28e85e44dc8f.png)

**Comment by the-m4a** [comment]
Thank you for the details!  It is very much appreciated.
I fixed a couple of issues with the DiplomacyDealScreen and the Banners and have uploaded it to the workshop.  I didn't get a chance to extensively test, so I'll look into that later tonight.  In the meantime, if you happen to see any difference in behavior with the updated version please let me know!

**Comment by CanuckMonkey** [comment]
I had just assumed that this was a new mode, "[Oops! All Baltimores](https://share.getcloudapp.com/p9u8nJeR)".

Seriously though, I came here to report the same problem.  Also playing Vanilla with only this mod and the Aztec DLC.

> I fixed a couple of issues with the DiplomacyDealScreen and the Banners and have uploaded it to the workshop. I didn't get a chance to extensively test, so I'll look into that later tonight. In the meantime, if you happen to see any difference in behavior with the updated version please let me know!

I'd like to help test if possible, do I need to do anything special?  I assume I should backup my existing mod folder and saved games, is there anything else?

**Comment by the-m4a** [comment]
The banners are different with vanilla and the expansions, so it may still be broken there.  Baltimore is the (for some reason) the default name assigned in the XML, so yeah all Baltimores is bad :)
I am remote at the moment so I can't look until later tonight.

When you start up a game, typically the Lua.log file should show issues.  On windows it's in the my docs/my games/Sid Meier's Civilization VI/Logs

**Comment by the-m4a** [comment]
These should be fixed now - let me know when you get the chance.  Thanks!

**Comment by CanuckMonkey** [comment]
I only had a few minutes but I loaded it up and played a couple of turns--everything appears to be back to normal now, thanks @the-m4a!

**Comment by Gliptal** [comment]
I checked out the issues that seem fixed after some quick testing. Can't easily check the relocation button for now. I have two specific cities that don't show yields on hover though, all other cities work fine. I'm unsure whether it's a new bug or I simply hadn't noticed before.

![yes](https://user-images.githubusercontent.com/3907646/106329793-5d913500-6282-11eb-80f9-7328ebf7419f.jpg)
![no](https://user-images.githubusercontent.com/3907646/106329797-5ec26200-6282-11eb-865a-fc8dd3e5ff0c.jpg)

**Comment by the-m4a** [comment]
@Gliptal any chance you can upload the save file?  That's strange for sure

**Comment by Gliptal** [comment]
Here it is:

[Savefile.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/5897090/Savefile.zip)

There's also something off with the production queue and the icon in the city banner, you can see an example in Hispalis in that save file: I still see the cog after queing a district. I think I saw different production times in the queue and the city banner as well, but didn't think about grabbing a screenshot.

**Comment by the-m4a** [comment]
Looking at it now: I indeed see the issue with the hover on Ravenna and Rome; Hispalis shows the Encampment is queued, so I'm not able to repro that issue.  I tried queuing the Encampment up behind a builder and let the builder complete, but it moved to the next item in the queue (the Encampment) correctly.

**Comment by cmhbob** [comment]
Joining in because I'm having similar issues. Epic base game getting CQUI via http://steamworkshop.download/. I updated it yesterday (1/31) and am having the Baltimore problem. lua.log attached per Reddit thread. 
[Lua.log](https://github.com/civfanatics/CQUI_Community-Edition/files/5905270/Lua.log)

**Comment by the-m4a** [comment]
Ah, interesting one!  @Gliptal I think you unearthed a bug that had been there a long time, it exists at least as far back as the file containing the issue has existed (about 8 months).
The bug is that if a city has no plots available to purchase (as Rome and Ravenna do not in your save), then it will not properly show those yields.  The code to show that stuff was hiding in an if statement it shouldn't have been.

I think I got that one figured out:
![image](https://user-images.githubusercontent.com/8787640/106433143-9ff27780-6424-11eb-9408-88b90c4178eb.png)

I'll push up the code changes into the m4a-jan2021updatesfix branch

(I wrote this comment last night and have no idea if it actually posted -- maybe this is an edit or maybe it is not I dunno)

**Comment by the-m4a** [comment]
@cmhbob - Looking now.  I downloaded the file from there and all the files inside are dated 9/16/20, and comparing files where I know the issue existed, I can see that the version I downloaded would indeed still have that bug...
Is there a way to force the thing to download the latest version?

**Comment by cmhbob** [comment]
Not sure. I'll go back and clear cache and cookies and see what I get.

**Comment by cmhbob** [comment]
> 
> 
> @cmhbob - Looking now. I downloaded the file from there and all the files inside are dated 9/16/20, and comparing files where I know the issue existed, I can see that the version I downloaded would indeed still have that bug...
> Is there a way to force the thing to download the latest version?

I cleared my cache at http://steamworkshop.download/ but got the same files again, dated 9/16/20, even though the site said it was updated 1/29/21. I moved over to https://steamworkshopdownloader.io/ and the files in the Zip were dated 2/2/21. That fixed it. I'm not sure how to tell the first site to refresh its files. Thanks for the help.

**Comment by Gliptal** [comment]
@the-m4a I can confirm cities with no plots available for purchase now show yields on hover! Excellent job, thanks!

That takes care of the last issue I came across with Jan update regarding cities.

**Comment by Gliptal** [comment]
@cmhbob I'm also playing on EGS, I think you're better off downloading the latest versione directly from github.

**Comment by the-m4a** [comment]
I noticed last night that there exists a version number field at the top of the modinfo file, something that I haven't made a habit of updating.  

Just posted a question to the CIv6 modding discord I somehow hadn't previously been aware of - Gedemon pointed me at https://steamworkshopdownloader.io/  -- I pulled the version from there and it is the one I uploaded on January 28th, the most recent!
