### ISSUE TITLE
Freezes under Linux

### ISSUE THREAD

**Issue by StragaSevera** [civfanatics/CQUI_Community-Edition#251]
**Describe the bug**
When I enable CQUI under Linux and start a game, the game freezes and I need to kill it manually.

**To Reproduce**
1. Start Civ6 under Linux.
2. Enable CQUI.
3. Start a new game.
4. The loading screen freezes.

**Expected behavior**
I expect the loading screen to end and game to start ;-)

**General informations**
 - OS: ArchLinux
 - Version: 1.0.9.9
 - Expansion: All

**Save game and logs**
[Logs.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/5942802/Logs.zip)

**Comment by the-m4a** [comment]
Is this with the Workshop version or the code currently checked into main?  It should work with the code checked into main, as there was an issue with both the DiplomacyDealView and CityBannerManager on Linux - basically they get into a loop of "including" one another and eventually it just runs out of memory

**Comment by StragaSevera** [comment]
It is with Workshop version. Will try the repository version and report.

**Comment by StragaSevera** [comment]
Nope, master hangs too.

**Comment by the-m4a** [comment]
sorry @StragaSevera  - main, not master... master is an outdated branch now.  (note to self: we need to delete the master branch)

if it hangs on _main_, then that would be surprising... as other folks with Linux have tried it out (before I pushed to main) and it worked ok.  Could be that it got messed up with the merge into main, but it shouldn't?

**Comment by StragaSevera** [comment]
No, main freezes as well. I can give you any logs or anything else to help you with debugging =-)

**Comment by the-m4a** [comment]
hmm.  weird.  :(   Linux for some reason or other does not produce a Lua.log file, so I typically end up debugging locally using y Windows instance of the Firaxis Live Tuner and the Windows-Subsystem-for-Linux in order to run Civ.  It runs ridiculously slow, but it runs - at least last I checked.  I don't think there's a Civ6 SDK for Linux - that'd be handy if so.

Are you running with CQUI as the only community mod?  Maybe it's a conflict with another mod...

**Comment by StragaSevera** [comment]
I think just installing the proper Linux distributive may be easier - you can set apart a tiny part of your hard drive and make an installation of Linux there. It's really easy =-)

Wow. I'm kinda speechless now. So, I had only one other mod - the Colorised Hostiroc Moments. I disabled it, and the game stopped freezing. I enabled it back, and it still does not freeze. So, I don't know what fixed the bug, but it is gone =-)

**Comment by the-m4a** [comment]
No worries. :)  I'll close this accordingly!
